
domain: &domain cloudnativeentrepreneur.dev
serviceName: &serviceName demo-app

expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: *domain
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-dev-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent
  keycloak:
    redirectUris:
      allowAll: false
      includeNamespace: true
      domain: *domain
      serviceName: *serviceName
