apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: {{ .Release.Namespace }}
spec:
  keycloak: sso
  realm: sso
  clientId: {{ .Release.Namespace }}
  clientType: confidential
  directAccessGrantsEnabled: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  redirectUris:
    - 'https://*'
  defaultRoles:
    - demo-app
  mapper:
    - name: audience
      protocolMapper: oidc-audience-mapper
      config:
        claim.name: audience
        access.token.claim: "true"
        included.client.audience: {{ .Release.Namespace }}
    - name: tenant
      protocolMapper: oidc-script-based-protocol-mapper
      config:
        claim.name: tenant
        access.token.claim: "true"
        jsonType.label: String
        script: "realm.getName();"
    - name: username
      protocolMapper: oidc-usermodel-property-mapper
      config:
        claim.name: username
        access.token.claim: "true"
        jsonType.label: String
        user.attribute: username
    - name: roles
      protocolMapper: oidc-usermodel-client-role-mapper
      config:
        claim.name: roles
        access.token.claim: "true"
        jsonType.label: String
        multivalued: "true"
        usermodel.clientRoleMapping.clientId: {{ .Release.Namespace }}