apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: {{ .Release.Namespace }}
spec:
  keycloak: sso
  realm: sso
  clientId: {{ .Release.Namespace }}
  clientType: confidential
  directAccessGrantsEnabled: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  redirectUris:
    - 'https://*'
  defaultRoles:
    - demo-app
  mapper:
    - name: audience
      protocolMapper: oidc-audience-mapper
      config:
        claim.name: audience
        access.token.claim: "true"
        included.client.audience: {{ .Release.Namespace }}
