apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    release: jenkins-x
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics